site_name: DeepTechRadar2026
site_url: https://christianchabrerie.github.io/DeepTechRadar2026/

theme:
  name: material
  features:
    - navigation.tabs

plugins:
  - search

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: markmap
          class: markmap
          format: !!python/name:pymdownx.superfences.fence_div_format

extra_javascript:
  - https://cdn.jsdelivr.net/npm/d3@7
  - https://cdn.jsdelivr.net/npm/markmap-lib@0.17.0
  - https://cdn.jsdelivr.net/npm/markmap-view@0.17.0
  - https://cdn.jsdelivr.net/npm/markmap-toolbar@0.17.0/dist/index.min.js
  - javascripts/markmap-loader.js

extra_css:
  - https://cdn.jsdelivr.net/npm/markmap-toolbar@0.17.0/dist/style.min.css
  - stylesheets/extra.css


