# Generated by ChatGPT 20260110
# Prompt : Convert .MM to .MD comptabile with https://markmap.js.org/repl

# Another version as been generated by gpt-oss-120b on a NVIDIA GDX GB10
# https://github.com/openai/gpt-oss

import xml.etree.ElementTree as ET

def mm_to_markdown(mm_file, md_file):
    tree = ET.parse(mm_file)
    root = tree.getroot()
    
    def parse_node(node, level=0):
        text = node.attrib.get('TEXT', '')
        if not text:
            return ''
        indent = '  ' * level  # 2 spaces per level
        md = f"{indent}- {text}\n"
        for child in node.findall('node'):
            md += parse_node(child, level + 1)
        return md
    
    # FreeMind usually has one main node
    main_node = root.find('node')
    markdown = parse_node(main_node)
    
    # Optionally, add main title
    markdown = f"# {main_node.attrib.get('TEXT', 'Mindmap')}\n" + markdown[markdown.find('\n')+1:]
    
    with open(md_file, 'w', encoding='utf-8') as f:
        f.write(markdown)

# Usage
mm_to_markdown('example.mm', 'example.md')
